"""Tests for buoy station coverage and NDBC/CDIP deduplication.

Two bugs, found by auditing live data against NDBC directly.

1. ndbc_stations.json was a hand-made file, six months stale, and knew about 74
   of the 146 wave-reporting stations within 120 km of a covered spot. That did
   not mean "a slightly worse buoy": BUOY_MAX_DISTANCE_KM is 320, and every
   Great Lakes spot's nearest KNOWN station was 400-600 km away across land, so
   Cleveland, Oswego and Buffalo returned an EMPTY list while live nearshore
   buoys sat 1.6 to 4 km offshore. The list is now generated by
   scripts/ndbc_station_scan.py and the Great Lakes distances are pinned below,
   because an empty buoy panel looks identical to a quiet upstream.

2. NDBC and CDIP both carry many of the same hulls, so every sampled spot
   listed one physical buoy twice -- 6 of 6, between 11 m and 308 m apart --
   with slightly different rounding on each. Side by side that reads as two
   instruments disagreeing about the same water.

The station-list assertions read the committed JSON and touch no network.
"""
import json
import os
import sys

import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import app  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


class _Fake:
    """Minimal stand-in for urlopen's return value."""

    def __init__(self, text):
        self._text = text

    def read(self):
        return self._text.encode('latin-1')



def _nearest_km(lat, lon):
    return min(app.haversine_distance(lat, lon, s['lat'], s['lon'])
               for s in app.NDBC_STATIONS)


class TestStationListIntegrity:
    def test_every_station_has_usable_fields(self):
        for s in app.NDBC_STATIONS:
            assert s.get('id'), s
            assert isinstance(s['lat'], (int, float))
            assert isinstance(s['lon'], (int, float))
            assert -90 <= s['lat'] <= 90 and -180 <= s['lon'] <= 180, s
            assert s.get('name')

    def test_no_duplicate_station_ids(self):
        ids = [str(s['id']) for s in app.NDBC_STATIONS]
        assert len(ids) == len(set(ids))

    def test_list_has_not_silently_shrunk(self):
        """A regenerate that half-fails must not quietly gut coverage."""
        assert len(app.NDBC_STATIONS) >= 250, (
            f"only {len(app.NDBC_STATIONS)} NDBC stations — did a scan write a "
            f"truncated list?")


class TestGreatLakesCoverage:
    """These spots returned NO buoys at all. The site advertises them."""

    # (name, lat, lon, max_km). Bounds are generous against the measured
    # distance so a buoy moving or being replaced does not fail the suite;
    # they exist to catch the list regressing to ocean-only again, which put
    # the nearest known station 400-600 km away.
    LAKE_SPOTS = [
        ('Cleveland Edgewater OH', 41.4906, -81.7326, 40),
        ('Oswego NY', 43.4691, -76.5160, 40),
        ('Milwaukee Bradford Beach WI', 43.0517, -87.8760, 40),
        ('Buffalo NY', 42.8770, -78.9050, 60),
        ('Presque Isle PA', 42.1639, -80.1151, 60),
        ('Chicago Montrose Beach IL', 41.9640, -87.6380, 60),
    ]

    @pytest.mark.parametrize('name,lat,lon,max_km', LAKE_SPOTS)
    def test_has_a_buoy_within_reach(self, name, lat, lon, max_km):
        km = _nearest_km(lat, lon)
        assert km <= max_km, (
            f"{name}: nearest NDBC station is {km:.0f} km — over "
            f"BUOY_MAX_DISTANCE_KM ({app.BUOY_MAX_DISTANCE_KM}) this spot shows "
            f"no buoys at all")

    @pytest.mark.parametrize('name,lat,lon,max_km', LAKE_SPOTS)
    def test_selection_actually_returns_one(self, name, lat, lon, max_km):
        found = app.find_nearest_buoys(lat, lon)
        assert found, f"{name}: find_nearest_buoys returned nothing"
        assert found[0]['distance_km'] <= max_km

    def test_ocean_spots_did_not_regress(self):
        for name, lat, lon in [('Surf City NC', 34.43, -77.55),
                               ('Pipeline HI', 21.665, -158.053),
                               ('Santa Cruz CA', 36.952, -122.025)]:
            assert _nearest_km(lat, lon) <= 60, name


class TestHullDeduplication:
    @staticmethod
    def _b(bid, source, lat, lon):
        return {'id': bid, 'source': source, 'name': bid,
                'lat': lat, 'lon': lon, 'distance_km': 10.0}

    def test_same_hull_from_both_networks_is_one_buoy(self):
        ndbc = self._b('41110', 'ndbc', 34.142, -77.715)
        cdip = self._b('150', 'cdip', 34.1416, -77.7147)     # 52 m away, real pair
        assert app._same_buoy(cdip, [ndbc]) is ndbc

    def test_distinct_buoys_are_not_merged(self):
        a = self._b('41110', 'ndbc', 34.142, -77.715)
        b = self._b('41159', 'ndbc', 34.211, -76.944)         # ~70 km
        assert app._same_buoy(b, [a]) is None

    def test_threshold_is_the_documented_one(self):
        a = self._b('A', 'ndbc', 34.0, -77.0)
        # ~0.5 km north: same hull. ~2 km north: not.
        close = self._b('B', 'cdip', 34.0045, -77.0)
        far = self._b('C', 'cdip', 34.018, -77.0)
        assert app._same_buoy(close, [a]) is a
        assert app._same_buoy(far, [a]) is None

    def test_empty_accepted_list_matches_nothing(self):
        assert app._same_buoy(self._b('A', 'ndbc', 34.0, -77.0), []) is None

    def test_endpoint_returns_no_duplicate_hulls(self, monkeypatch):
        """The whole point: three slots, three different buoys."""
        pairs = [
            self._b('41110', 'ndbc', 34.142, -77.715),
            self._b('150', 'cdip', 34.1416, -77.7147),       # duplicate hull
            self._b('41159', 'ndbc', 34.211, -76.944),
            self._b('41108', 'ndbc', 34.5, -77.0),
        ]
        monkeypatch.setattr(app, 'find_nearest_buoys',
                            lambda lat, lon, count=3: list(pairs))
        monkeypatch.setattr(app, '_fetch_ndbc_observation',
                            lambda bid: {'wave_height': 1.0})
        monkeypatch.setattr(app, '_fetch_cdip_observation',
                            lambda bid: {'wave_height': 1.0})
        for fn in ('_fetch_ndbc_spectrum', '_fetch_ndbc_directional',
                   '_fetch_cdip_spectrum', '_fetch_cdip_directional'):
            monkeypatch.setattr(app, fn, lambda bid: None)

        got = app.get_buoy_data(34.43, -77.55)['buoys']
        ids = [b['id'] for b in got]
        assert '150' not in ids, "CDIP twin of 41110 should have been dropped"
        assert ids == ['41110', '41159', '41108']

    def test_a_dead_primary_still_leaves_the_hull_represented(self, monkeypatch):
        """First WITH DATA wins, so one network being down is survivable."""
        monkeypatch.setattr(app, 'find_nearest_buoys', lambda lat, lon, count=3: [
            self._b('41110', 'ndbc', 34.142, -77.715),
            self._b('150', 'cdip', 34.1416, -77.7147),
        ])
        monkeypatch.setattr(app, '_fetch_ndbc_observation', lambda bid: None)
        monkeypatch.setattr(app, '_fetch_cdip_observation',
                            lambda bid: {'wave_height': 1.0})
        for fn in ('_fetch_ndbc_spectrum', '_fetch_ndbc_directional',
                   '_fetch_cdip_spectrum', '_fetch_cdip_directional'):
            monkeypatch.setattr(app, fn, lambda bid: None)
        got = app.get_buoy_data(34.43, -77.55)['buoys']
        assert [b['id'] for b in got] == ['150']


class TestStationScanScript:
    """scripts/ndbc_station_scan.py rewrites a committed data file unattended.

    The failure that matters is not a crash, it is a scan that half-works and
    writes a truncated list: the site would keep serving, with buoys quietly
    missing, and nothing would look wrong.
    """

    def _module(self):
        import importlib.util
        path = os.path.join(ROOT, 'scripts', 'ndbc_station_scan.py')
        spec = importlib.util.spec_from_file_location('ndbc_station_scan', path)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        return mod

    def test_wave_capability_needs_a_wvht_column(self):
        m = self._module()
        no_waves = ("#YY  MM DD hh mm WDIR WSPD GST PRES ATMP\n"
                    "#yr  mo dy hr mn degT  m/s m/s  hPa degC\n"
                    "2026 08 25 13 00  180  5.0 6.0 1015 25.0\n")
        assert m.reports_waves('x', lambda url, timeout=0: _Fake(no_waves)) is False

    def test_column_present_but_never_populated_is_not_capable(self):
        m = self._module()
        all_missing = ("#YY  MM DD hh mm WVHT  DPD\n"
                       "#yr  mo dy hr mn    m  sec\n"
                       "2026 08 25 13 00   MM   MM\n"
                       "2026 08 25 12 30   MM   MM\n")
        assert m.reports_waves('x', lambda url, timeout=0: _Fake(all_missing)) is False

    def test_one_real_value_anywhere_counts_as_capable(self):
        """A buoy ashore for servicing must not be deleted from the list."""
        m = self._module()
        mostly_missing = ("#YY  MM DD hh mm WVHT  DPD\n"
                          "#yr  mo dy hr mn    m  sec\n"
                          "2026 08 25 13 00   MM   MM\n"
                          "2026 08 20 13 00  1.2    6\n")
        assert m.reports_waves('x', lambda url, timeout=0: _Fake(mostly_missing)) is True

    def test_unreachable_station_is_not_capable(self):
        m = self._module()

        def boom(url, timeout=0):
            raise OSError('connection refused')
        assert m.reports_waves('x', boom) is False

    def test_build_keeps_only_capable_stations(self):
        m = self._module()
        active = {
            'A': {'id': 'A', 'lat': 34.0, 'lon': -77.0, 'name': 'A'},
            'B': {'id': 'B', 'lat': 35.0, 'lon': -76.0, 'name': 'B'},
        }
        keep, probed = m.build(active, probe=lambda sid: sid == 'A', workers=2)
        assert probed == 2
        assert [s['id'] for s in keep] == ['A']

    def test_stations_without_coordinates_are_dropped(self):
        m = self._module()
        xml = ('<stations>'
               '<station id="A" lat="34.0" lon="-77.0" name="good"/>'
               '<station id="B" lat="" lon="" name="bad"/>'
               '<station id="C" name="missing"/>'
               '</stations>')
        got = m.fetch_active_stations(lambda url, timeout=0: _Fake(xml))
        assert list(got) == ['A']
